name: Setup Environment
description: Sets up Node.js, Yarn, and EAS CLI for Expo projects

inputs:
    node-version:
        description: "Node.js version to use"
        required: true

    working-directory:
        description: "Working directory for the project"
        required: true

runs:
    using: "composite"
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Cache node_modules
          uses: actions/cache@v4
          with:
              path: ${{ inputs.working-directory }}/node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles(format('{0}/package.json', inputs.working-directory), format('{0}/yarn.lock', inputs.working-directory)) }}
              restore-keys: |
                  ${{ runner.os }}-node-modules-

        - name: Install dependencies
          run: yarn install
          shell: bash
          working-directory: ${{ inputs.working-directory }}
