name: Setup Environment
description: Sets up Node.js, Bun, and EAS CLI for Expo projects
inputs:
    node-version:
        description: "Node.js version to use"
        required: true
    bun-version:
        description: "Bun version to install"
        required: false
        default: "latest"
    working-directory:
        description: "Working directory for the project"
        required: true
    expo-token:
        description: "Expo token for EAS authentication"
        required: true
    build-type:
        description: "Build type: 'local' or 'remote' (cloud)"
        required: false
        default: "local"

runs:
    using: "composite"
    steps:
        - name: Setup Bun
          uses: oven-sh/setup-bun@v1
          with:
              bun-version: ${{ inputs.bun-version }}

        - name: Cache dependencies
          if: inputs.build-type == 'local'
          uses: actions/cache@v4
          id: cache-dependencies
          with:
              path: |
                  ~/.bun/install/cache
                  ${{ inputs.working-directory }}/node_modules
              key: bun-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles(format('{0}/bun.lockb', inputs.working-directory)) }}
              restore-keys: |
                  bun-${{ runner.os }}-${{ inputs.node-version }}-

        - name: Install dependencies
          run: bun install --frozen-lockfile
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          if: steps.cache-dependencies.outputs.cache-hit != 'true'

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
              eas-version: latest
              token: ${{ inputs.expo-token }}
              working-directory: ${{ inputs.working-directory }}
