name: Setup Environment
description: Sets up Node.js, Yarn, and EAS CLI for Expo projects

inputs:
    node-version:
        description: "Node.js version to use"
        required: true

    working-directory:
        description: "Working directory for the project"
        required: true

    expo-token:
        description: "Expo token for EAS authentication"
        required: true

runs:
    using: "composite"
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
              eas-version: latest
              token: ${{ inputs.expo-token }}
              working-directory: ${{ inputs.working-directory }}

        - name: Install dependencies
          run: yarn install
          shell: bash
          working-directory: ${{ inputs.working-directory }}
