name: Build APK
on:
    workflow_call:
        inputs:
            node-version:
                description: "Node.js version to use"
                required: true
                type: string
            bun-version:
                description: "Bun version to install"
                required: false
                type: string
                default: "latest"
            working-directory:
                description: "Working directory for the project"
                required: true
                type: string
        secrets:
            EXPO_TOKEN:
                description: "Expo token for EAS authentication"
                required: true
            API_URL:
                description: "API URL for the app"
                required: false

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: ${{ inputs.node-version }}
                  bun-version: ${{ inputs.bun-version }}
                  working-directory: ${{ inputs.working-directory }}
                  expo-token: ${{ secrets.EXPO_TOKEN }}

            - name: Build Android app
              run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.apk
