name: Build APK
on:
    workflow_call:
        inputs:
            node-version:
                description: "Node.js version to use"
                required: true
                type: string
            bun-version:
                description: "Bun version to install"
                required: false
                type: string
                default: "latest"
            working-directory:
                description: "Working directory for the project"
                required: true
                type: string
        secrets:
            EXPO_TOKEN:
                description: "Expo token for EAS authentication"
                required: true
            EXPO_PUBLIC_APP_TOKEN:
                description: "Expo token for EAS authentication"
                required: true
            EXPO_PUBLIC_API_ENDPOINT:
                description: "Expo token for EAS authentication"
                required: true
            EXPO_PUBLIC_CLOUDINARY_DOMAIN:
                description: "Expo token for EAS authentication"
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: ${{ inputs.node-version }}
                  bun-version: ${{ inputs.bun-version }}
                  working-directory: ${{ inputs.working-directory }}
                  expo-token: ${{ secrets.EXPO_TOKEN }}

            - name: Validate environment variables
              run: |
                  if [ -z "$EXPO_PUBLIC_API_ENDPOINT" ]; then
                      echo "Error: EXPO_PUBLIC_API_ENDPOINT is not set"
                      exit 1
                  fi
                  if [ -z "$EXPO_PUBLIC_APP_TOKEN" ]; then
                      echo "Error: EXPO_PUBLIC_APP_TOKEN is not set"
                      exit 1
                  fi
                  if [ -z "$EXPO_PUBLIC_CLOUDINARY_DOMAIN" ]; then
                      echo "Error: EXPO_PUBLIC_CLOUDINARY_DOMAIN is not set"
                      exit 1
                  fi
              env:
                  EXPO_PUBLIC_API_ENDPOINT: ${{ secrets.EXPO_PUBLIC_API_ENDPOINT }}
                  EXPO_PUBLIC_APP_TOKEN: ${{ secrets.EXPO_PUBLIC_APP_TOKEN }}
                  EXPO_PUBLIC_CLOUDINARY_DOMAIN: ${{ secrets.EXPO_PUBLIC_CLOUDINARY_DOMAIN }}
            - name: Build Android app
              run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk
              env:
                  EXPO_PUBLIC_APP_TOKEN: ${{ secrets.EXPO_PUBLIC_APP_TOKEN}}
                  EXPO_PUBLIC_API_ENDPOINT: ${{ secrets.EXPO_PUBLIC_API_ENDPOINT}}
                  EXPO_PUBLIC_CLOUDINARY_DOMAIN: ${{ secrets.EXPO_PUBLIC_CLOUDINARY_DOMAIN}}

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4

              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.apk
