name: Build APK
on:
    workflow_call:
        inputs:
            node-version:
                description: "Node.js version to use"
                required: true
                type: string
            bun-version:
                description: "Bun version to install"
                required: false
                type: string
                default: "latest"
            working-directory:
                description: "Working directory for the project"
                required: true
                type: string
            build-type:
                description: "Build type: 'local' or 'remote' (cloud)"
                required: false
                type: string
                default: "local"

        secrets:
            EXPO_TOKEN:
                description: "Expo token for EAS authentication"
                required: true
            EXPO_PUBLIC_APP_TOKEN:
                description: "Expo app token for configuration"
                required: true
            EXPO_PUBLIC_API_ENDPOINT:
                description: "API endpoint for the app"
                required: true
            EXPO_PUBLIC_CLOUDINARY_DOMAIN:
                description: "Cloudinary domain for media"
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        timeout-minutes: 60
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: ${{ inputs.node-version }}
                  working-directory: ${{ inputs.working-directory }}
                  expo-token: ${{ secrets.EXPO_TOKEN }}
                  build-type: ${{ inputs.build-type }}

            - name: Build Android app
              run: |
                  if [ "${{ inputs.build-type }}" = "local" ]; then
                    eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk
                  else
                    eas build --platform android --profile preview2 --non-interactive --wait
                  fi
              env:
                  EXPO_PUBLIC_APP_TOKEN: ${{ secrets.EXPO_PUBLIC_APP_TOKEN }}
                  EXPO_PUBLIC_API_ENDPOINT: ${{ secrets.EXPO_PUBLIC_API_ENDPOINT }}
                  EXPO_PUBLIC_CLOUDINARY_DOMAIN: ${{ secrets.EXPO_PUBLIC_CLOUDINARY_DOMAIN }}

            - name: Get Latest Build Info (JSON)
              if: inputs.build-type == 'remote'
              id: latest-build
              run: |
                  BUILD_JSON=$(eas build:list --platform android --limit 1 --status=finished --json)
                  echo "build_json=$BUILD_JSON" >> "$GITHUB_OUTPUT      "

            - name: Extract APK URL
              if: inputs.build-type == 'remote'
              id: extract-url
              run: |
                  echo "${{ steps.latest-build.outputs.build_json }}" > build.json
                  APK_URL=$(jq -r '.[0].artifacts.buildUrl // .[0].artifacts.apk' build.json)
                  echo "APK_URL=$APK_URL" >> $GITHUB_ENV
                  echo "apk_url=$APK_URL" >> "$GITHUB_OUTPUT"

            - name: Download APK
              if: inputs.build-type == 'remote'
              run: |
                  curl -L "$APK_URL" -o app-release.apk
                  ls -lh app-release.apk

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.apk
                  retention-days: 7

            - name: Post PR comment on success
              if: success() && github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: '✅ APK build completed successfully! Check the artifacts for the APK. (${{ inputs.build-type }})'
                      })

            - name: Post PR comment on failure
              if: failure() && github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: '❌ APK build failed. Please check the workflow logs for details. (${{ inputs.build-type }})'
                      })
