name: EAS Build and Deploy

on:
    pull_request:
        branches: [dev, stag, main]
    push:
        branches: [dev, stag, main, "hotfix/**"]
        tags:
            - "hotfix/**"

jobs:
    check-lint:
        name: Check Lint
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: "20.x"
                  working-directory: ./health-pal

            - name: Run lint
              working-directory: ./health-pal
              run: yarn lint

    check-unit-test:
        name: Check Unit test
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: "20.x"
                  working-directory: ./health-pal

            - name: Run unit test
              working-directory: ./health-pal
              run: yarn test

    preview:
        name: PR Preview
        needs: [check-lint, check-unit-test]
        if: github.event_name == 'pull_request' && github.base_ref != 'main'
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: "20.x"
                  working-directory: ./health-pal

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}
                  working-directory: ./health-pal
                  expo-version: latest

            - name: Determine build profile
              id: vars
              run: |
                  BRANCH="${GITHUB_REF#refs/heads/}"
                  PROFILE=""
                  case "$BRANCH" in
                    dev) PROFILE="development" ;;
                    stag) PROFILE="staging" ;;
                    main) PROFILE="production" ;;
                    *) PROFILE="preview" ;;
                  esac
                  echo "profile=$PROFILE" >> $GITHUB_OUTPUT

            - name: Run EAS Preview
              uses: expo/expo-github-action/preview@v8
              with:
                  working-directory: ./health-pal
                  command: eas update --auto --channel ${{ steps.vars.outputs.profile }}
              env:
                  EXPO_PUBLIC_APP_TOKEN: ${{ secrets.EXPO_PUBLIC_APP_TOKEN }}
                  EXPO_PUBLIC_API_ENDPOINT: ${{ secrets.EXPO_PUBLIC_API_ENDPOINT }}
                  EXPO_PUBLIC_CLOUDINARY_DOMAIN: ${{ secrets.EXPO_PUBLIC_CLOUDINARY_DOMAIN }}

            - name: Post PR comment
              if: always()
              uses: actions/github-script@v7
              with:
                  script: |
                      const buildStatus = ${{ job.status == 'success' }} ? '✅ Build completed successfully! Check artifacts for APK.' : '❌ Build failed. Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
                      const easStatus = ${{ steps.eas-preview.outcome == 'success' }} ? '✅ EAS Update completed! Preview ready.' : '❌ EAS Update failed or skipped. Check logs.';
                      github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: `${buildStatus}\n${easStatus}`
                      });

    build:
        name: CI Build
        needs: [check-unit-test]
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'dev')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: "20.x"
                  working-directory: ./health-pal

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}
                  working-directory: ./health-pal

            - name: Determine build profile
              id: vars
              run: |
                  BRANCH="${GITHUB_REF#refs/heads/}"
                  PROFILE=""
                  case "$BRANCH" in
                    dev) PROFILE="development" ;;
                    stag) PROFILE="staging" ;;
                    main) PROFILE="production" ;;
                    *) PROFILE="preview" ;;
                  esac
                  echo "profile=$PROFILE" >> $GITHUB_OUTPUT

            - name: EAS Build
              run: eas build --platform android --profile ${{ steps.vars.outputs.profile }} --non-interactive
              working-directory: ./health-pal

    deploy_hotfix:
        name: Deploy OTA Update for Hotfix
        if: startsWith(github.ref, 'refs/tags/hotfix/') || startsWith(github.ref, 'refs/heads/hotfix/')
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  node-version: "20.x"
                  working-directory: ./health-pal

            - name: EAS Login
              run: eas login --token ${{ secrets.EAS_TOKEN }}

            - name: Run OTA Update
              run: eas update --branch main --channel production --message "Hotfix update from ${{ github.ref }}"
