name: Build APK
on:
    workflow_call:
        inputs:
            node-version:
                description: "Node.js version to use"
                required: true
                type: string
            bun-version:
                description: "Bun version to install"
                required: false
                type: string
                default: "latest"
            working-directory:
                description: "Working directory for the project"
                required: true
                type: string
        secrets:
            EXPO_TOKEN:
                description: "Expo token for EAS authentication"
                required: true

jobs:
    setup:
        name: Setup Environment
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Cache node modules
              uses: actions/cache@v4
              id: cache-node-modules
              with:
                  path: ~/.bun/install/cache
                  key: bun-${{ hashFiles('${{ inputs.working-directory }}/bun.lockb') }}

            - name: Install dependencies if cache not present
              run: bun install --frozen-lockfile
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
